version: '3.9'

services:
  # Laravel App (PHP-FPM + Nginx + Supervisor)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zay_shop_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: zay_shop_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""     # root không mật khẩu (trùng với .env)
      MYSQL_DATABASE: laravel_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: zay_shop_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""     # trùng với db config
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
